In [1]:
import torch

In [2]:
x = torch.rand(1, 3, 4)


In [3]:
x

tensor([[[0.5406, 0.6339, 0.9407, 0.2911],
         [0.4695, 0.6397, 0.9372, 0.0689],
         [0.1483, 0.0441, 0.9890, 0.9906]]])

In [4]:
x.shape

torch.Size([1, 3, 4])

In [5]:
arrange = torch.arange(110)


In [6]:
arrange

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [7]:
ten = torch.tensor([[1,3,5.2],
 [8, 9, 10], [5, 6, 2]])

In [8]:
ten

tensor([[ 1.0000,  3.0000,  5.2000],
        [ 8.0000,  9.0000, 10.0000],
        [ 5.0000,  6.0000,  2.0000]])

In [9]:
print(ten.shape)

torch.Size([3, 3])


In [10]:
ten.dtype

torch.float32

In [11]:
a = torch.tensor([[1, 2], [3, 4]])

In [12]:
b = torch.tensor([[1, 2], [3, 4]])

In [13]:
a*b

tensor([[ 1,  4],
        [ 9, 16]])

In [14]:
a @ b

tensor([[ 7, 10],
        [15, 22]])

In [15]:
reshape = a.reshape(1, -1)

In [16]:
reshape

tensor([[1, 2, 3, 4]])

In [17]:
b = a.flatten()


In [18]:
print(b == reshape)

tensor([[True, True, True, True]])


In [19]:
c = torch.tensor([3,1])

In [20]:
c.shape

torch.Size([2])

In [21]:
x = torch.tensor([1,2,3])

In [54]:
d = torch.rand(1,4)
# d.dim()
d


tensor([[0.6778, 0.8129, 0.1232, 0.9660]])

In [59]:
d.squeeze(-2).ndim

1

In [56]:
d.ndim

2

In [60]:
# x = torch.arange(24)
# Convert it to shape (4, 6).
# Convert it to shape (2, 3, 4).
# Flatten it back to one dimension.
# Print the third row.
# Print the last column.
# Print only rows 2–4 and columns 3–6 (using slicing).


In [61]:
x = torch.arange(24)

In [63]:
x = x.reshape(4,6)
x.reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [66]:
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [68]:
# Print 3rd row
x[2, :]

tensor([12, 13, 14, 15, 16, 17])

In [69]:
# Print Last column

x[:,-1]

tensor([ 5, 11, 17, 23])

In [70]:
# Print only rows 2–4 and columns 3–6

x[2:4, 3:6]

tensor([[15, 16, 17],
        [21, 22, 23]])